### ISSUE TITLE
any left for selling ?

### ISSUE THREAD

**Issue by Bragir** [JDet-74/C128toSCART_SMT#1]
Do you have any left for selling ?
If so then i would like to buy an option 3 (the complete finished and tested adapter)
and one of each of the cables (din-8, sub-d-9 and scart cable)
option 3             -  38.00€
din8                    -    9.00€
sub D9               -     3.00€
Scart                  -     2.00€
Shipment(EU)   -    15.00€

total                  -    67.00€

**Comment by JDet-74** [comment]
Hey @Bragir 
I have to build some devices. 
Currently, I am out of stock :)
Where do you live? 
Maybe the shipping costs are cheaper.
Please send a mail to kernelpanic_74@yahoo.de with your address.
