### ISSUE TITLE
Hey rockstar..

### ISSUE THREAD

**Issue by Paulie420** [JDet-74/C128toSCART_SMT#2]
I’d love to grab a full complete c=128 to scart, a scart cable and a serial cable. 

I’m in Portland, Oregon, USA And think shipping is 31. I can up with 77 or so, but I’d love to order and pay if you’re in mood to make some smoke.

**Comment by JDet-74** [comment]
Hey @Paulie420 

I've just made a couple of C128toSCART devices again.
Unfortunately, the DIN8 cables are currently out. I have to order this again first. I know a guy who soldered them for 9 EUR.
If you only want the C128toSCART device, the D-SUB9 cable and the SCART cable, then I can send everything to you immediately.
The shipping costs to the USA are ridiculously expensive at the moment.
In the middle of March, I sent a package to Adrian Black (https://www.youtube.com/user/craig1black) in Portland. That was a 2kg (70.54792 Oz) package and cost 20 EUR. I have to clarify what the cheapest shipping option to the USA is. The package will only weigh around 500g (17.63698 Oz) and it will likely be cheaper. Do you want a shipping method that is trackable or not?
Send me a message to kernelpanic_74@yahoo.de with your address and I will send everything to you.

**Comment by Paulie420** [comment]
the DIN8 cable is just... a DIN8 cable on both ends? i could prolly order on amazon??? emailing you
